---
- name: Configure KVM base image
  hosts: localhost
  gather_facts: True
  become: yes
  roles:
    - common

- name: Install VPP 
  hosts: localhost
  gather_facts: True
  become: yes
  roles:
    - vpp-install

- name: Install FRR
  hosts: localhost
  roles:
    - mrlesmithjr.frr
  vars:
    frr_version: 8.4.2
